### ISSUE TITLE
Should ServiceLoader in ContainerProvider defer Throwable and continue the iteration?

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/websocket-api#254]
A question that arose from looking at Issue #250

Currently the ServiceLoader implementation in ContainerProvider can produce a variety of exceptions / throwables outside of what's documented by ContainerProvider.

(Really, the Error behavior is documented in ServiceLoader itself)

The question here is related to what happens when there are more then 1 ContainerProvider and one of them has an error/issue?

example:

    com.company.BadContainerProvider
    com.company.GoodContainerProvider

Lets assume `com.company.BadContainerProvider` cannot be loaded for some reason (eg: Its compiled in Java 9 bytecode and we are on a Java 8 runtime)

Lets also assume that Classloader returns `com.company.BadContainerProvider` first, then `com.company.GoodContainerProvider`.

This is a proposal to ask if it would be worth deferring the Throwable from the load of `com.company.BadContainerProvider` so that `com.company.GoodContainerProvider` could get a chance to be the `ContainerProvider` implementation?

If no good implementation is found, then the deferred Throwable is actually thrown.

**Comment by markt-asf** [comment]
I've been reading through the Javadoc for `ServiceLoader`. The short version is that once the first `ServiceConfigurationError` occurs subsequent use will be on a best efforts basis and recovery can't be guaranteed. It also says that anything that triggers a `ServiceConfigurationError` is a "serious problem".
So it seems the answer is "we can continue if we want to". So, do we want to?
I think I am leaning towards not continuing. I'd prefer to see the user take explicit action to either fix the error or exclude that provider rather than the API code effectively deciding that excluding the provider is the right thing to do. I'm not sure it would be in all circumstances.
Thoughts?

**Comment by joakime** [comment]
I'm happy with the decision to allow `ServiceConfigurationError` to flow out of the `ContainerProvider.getWebSocketContainer()`.
